# Generated by Django 4.2 on 2025-02-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                ("server_response", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Start Date and Time"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "ежедневно"),
                            ("weekly", "раз в неделю"),
                            ("monthly", "раз в месяц"),
                            ("yearly", "раз в год"),
                        ],
                        default="weekly",
                        max_length=250,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создана"),
                            ("running", "в работе"),
                            ("completed", "выполнена"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("body", models.TextField(verbose_name="Body")),
            ],
        ),
    ]
