# Generated by Django 4.2 on 2025-02-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="End Date and Time"
            ),
        ),
    ]
