# Generated by Django 4.2 on 2025-02-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_mailing_end_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailings.mailing",
            ),
        ),
    ]
